### ISSUE TITLE
No incoming calls without Google Play Services

### ISSUE THREAD

**Issue by geileszeuch** [WhisperSystems/RedPhone#296]
I do not have Google Play Services installed on my device. I have set the Signaling Method to SMS, but when people try to call me they get a 'Server failed' message. I am aware that this might be caused by a firewall or bad signal, but I tested this with two phones in the same WiFi. One phone having GCM and the other not. It was no problem calling the phone with GCM in this environment, but it was not possible to call the phone without GCM.

**Comment by dillbyrne** [comment]
I'm also experiencing this. The phone with no google apps can call out but cannot receive calls. I'm on beta 1.0.3. Thank you for all the hard work.

**Comment by moxie0** [comment]
Google Play Services is required for RedPhone to receive calls.

**Comment by dillbyrne** [comment]
@moxie0 Thanks for confirming and to the team at whisper systems for the hard work.
