### ISSUE TITLE
contacts 

### ISSUE THREAD

**Issue by YvonneKoechig** [WhisperSystems/RedPhone#370]
Impossible to add contacts
Please advise.
thank  you
regards,
Yvonne

**Comment by WhiteHatTux** [comment]
Hi @YvonneKoechig, 

You don't actually "add" a contact. Once it is possible to talk to them via Redphone(or Signal on iOS) that contact will automatically appear. 

So once a contact in your normal phone contacts installs Redphone (or Signal on iOS) and registers their number (that you have in your contacts) with Redphone, he or she will appear in your contact list.

Best regards
WhiteHatTux

**Comment by YvonneKoechig** [comment]
Good Evening WhiteHatTux,
Thank you for your reply. 
My Redphone world is just fine now...since I actually added the numbers into my contact list. 
Let's chalk this one up as a false alarm. 
Redphone is nifty. 
Keep up the good work.

Best regards,
Yvonne
