### ISSUE TITLE
Can't import contact. dialed is ALL wrong!

### ISSUE THREAD

**Issue by tbsruths** [WhisperSystems/RedPhone#376]
samsung galaxy s2 i9100
Redphone claimes i have no contacs, nor gives me the option to import.
it says i make a call at MAY & JULY 2014, which is false.
i CAN call myself: the device that dials is also *the same one* to recive the call. i can't answer.

What is the EXACT encryption the app is using?

**Comment by moxie0** [comment]
For support questions, please visit the support center: http://support.whispersystems.org
