### ISSUE TITLE
cannot register redphone

### ISSUE THREAD

**Issue by akaolf** [WhisperSystems/RedPhone#430]
Hi, 
I receive sms but nothing happen after that. 
It start again and again with registration.
I cannot register by voice, or I do not know how.
It is any place when I can do it manually ?
Thank you.

**Comment by peterpanondrugs** [comment]
Kinda Same problem. i dont get the SMS.

**Comment by daddo38** [comment]
Also same issue - no sms.

**Comment by daddo38** [comment]
Connectivity error.
RedPhone was unable to connect to the switch.

**Comment by daddo38** [comment]
It worked now.

**Comment by akaolf** [comment]
Yes, somehow..it worked today!
